import ContextProvider from '@/providers/ContextProvider'
import TanstackProvider from '@/providers/TanstackProvider'
import Header from '@/ui/Header'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'react-loading-skeleton/dist/skeleton.css'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (

    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <ReactQueryDevtools />
          <ContextProvider>
            {< Header />}
            {children}
          </ContextProvider>
        </TanstackProvider>
      </body>
    </html>

  )
}
